# Generated by Django 4.2.7 on 2024-09-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sodienthangtruoc', models.BigIntegerField(default=0)),
                ('sonuocthangtruoc', models.BigIntegerField(default=0)),
                ('sodienthangnay', models.BigIntegerField(default=0)),
                ('sonuocthangnay', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Congno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.CharField(max_length=255)),
                ('tiennuoc', models.BigIntegerField(default=0)),
                ('tiendien', models.BigIntegerField(default=0)),
                ('trangthai', models.BooleanField(default=False)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phong', to='myHouse.phong')),
            ],
        ),
    ]
