# Generated by Django 4.2.7 on 2024-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHouse', '0002_alter_phong_sodienthangnay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congno',
            name='sodien',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congno',
            name='sonuoc',
            field=models.BigIntegerField(default=0),
        ),
    ]
