# Generated by Django 4.2.7 on 2024-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHouse', '0003_congno_sodien_congno_sonuoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congno',
            name='sodien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='congno',
            name='sonuoc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='congno',
            name='tiendien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='congno',
            name='tiennuoc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='phong',
            name='sodienthangnay',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='sodienthangtruoc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='phong',
            name='sonuocthangnay',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
        migrations.AlterField(
            model_name='phong',
            name='sonuocthangtruoc',
            field=models.FloatField(default=0),
        ),
    ]
