# Generated by Django 4.2.7 on 2024-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHouse', '0007_phong_stt_phong_vitri'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='no',
            field=models.FloatField(default=0),
        ),
    ]
